cust_app_web/blueprints/users/views.py
from flask import request, Blueprint, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash
from peewee import IntegrityError
from models.user import User
from flask_login import current_user, login_required, logout_user, login_user

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/', methods=['GET'])
@login_required
def index():
    if current_user.is_active:
        return render_template('userpage.html', username=current_user.username)
    else:
        return render_template(url_for('user.login'))

@users_blueprint.route('/sign_up', methods=['GET'])
def sign_up():
    if current_user.is_active:
        return redirect(url_for('home'))
    return render_template('signup form.html')


@users_blueprint.route('/sign_up_form', methods=['POST'])
def create():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    new_user = User(username=username, password=password, email=email)

    try:
        new_user.save()
        flash("Successfully Created")
        login_user(new_user)
        return redirect(url_for("users.show", username=current_user.username))

    except IntegrityError as e:
        if 'username' in str(e):
            return render_template('signup form.html', username=request.form['username'], errors='Username is taken')
        if 'email' in str(e):
            return render_template('signup form.html', email=request.form['email'], errors='Email is taken')

@users_blueprint.route('/sign_in', methods=['GET'])
def sign_in():
    if current_user.is_active:
        return redirect(url_for("users.show", username=current_user.username))
    return render_template('signin form.html')

@users_blueprint.route('/sign_in_form', methods=['POST'])
def user_show():
    current_username = request.form.get('username')
    current_password = request.form.get('password')
    current_person = User.get_or_none(User.username == current_username)

    if current_person != None:
        if current_person.login_validate(current_password):
            login_user(current_person)
            flash('Successfully signed in')
            return redirect(url_for('users.show', username=current_username))
        else:
            return render_template('signin form.html', errors=current_person.errors)
    else:
        flash('Username not found! Please sign up for an account.')
        return render_template('signin form.html')

@users_blueprint.route('/<username>', methods=["GET"])
@login_required
def show(username):
    if current_user.is_active:
        return render_template('userpage.html', username=current_user.username)
    else:
        return render_template(url_for('user.login'))

@users_blueprint.route('/logout', methods=["GET"])
@login_required
def logout():
    logout_user()
    flash('Successfully logged out')
    return redirect(url_for('home'))

cust_app_web/blueprints/users/templates/users/signin form.html
{% extends "_layout.html" %}
{% block title %}
Sign In
{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<h1>Sign In</h1>

<form action="{{ url_for('users.user_show') }}" method='POST'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group">
        <label for="username">Username:</label>
        <input type='text' name='username' class="form-control" />
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input type='password' name='password' class="form-control" />
    </div>

    {% for error in errors if errors | length > 0 %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">x</span></button>
        {{error}}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Log In</button>
</form>





{% endblock %}

cust_app_web/blueprints/users/templates/users/signup form.html
{% extends "_layout.html" %}
{% block title %}
Sign Up
{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<h1>Sign Up</h1>

<form action="{{ url_for('users.create') }}" method='POST'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group">
        <label for="username">Username:</label>
        <input type='text' name='username' class="form-control" />
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input type='password' name='password' class="form-control" />
    </div>

    <div class="form-group">
        <label for="email">Email:</label>
        <input type='text' name='email' class="form-control" />
    </div>

    {% for error in errors if errors | length > 0 %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">x</span></button>
        {{error}}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Create Account</button>
</form>
{% endblock %}

cust_app_web/blueprints/users/templates/users/userpage.html
{% extends "_layout.html" %}
{% block title %}
{{ username }}'s page
{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<h1>{{ username }}'s page</h1>
<p><a href="{{ url_for('home') }}" class="btn">Home</a></p>

{% if current_user.is_authenticated %}


<p><a href="{{ url_for('users.logout') }}" class="btn">Log Out</a></p>
{% endif %}

{% for error in errors if errors | length > 0 %}
<div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
            aria-hidden="true">x</span></button>
    {{error}}
</div>
{% endfor %}
{% endblock %}

<!-- <p><a href="{{ url_for('users.edit', uid=current_user.id) }}" class="btn">Update details</a></p> -->